version: '3'
services:
  auth:
    build: .
    working_dir: /auth_service
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./auth_service:/auth_service
    ports:
      - "8001:8000"
    depends_on:
      - broker

  task:
    build: .
    working_dir: /task_service
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./task_service:/task_service
    ports:
      - "8002:8000"
    depends_on:
      - broker

  accounting:
    build: .
    working_dir: /accounting_service
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./accounting_service:/accounting_service
    ports:
      - "8003:8000"
    depends_on:
      - broker

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:2181"]
      interval: 30s
      timeout: 10s
      retries: 5

  broker:
    image: confluentinc/cp-kafka:latest
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9092"]
      interval: 2s
      timeout: 10s
      retries: 15
    depends_on:
      - zookeeper

  redis:
    restart: on-failure
    image: "redis:alpine"

  task_celery:
    restart: on-failure
    build: .
    working_dir: /popug_area/task_service
    command: bash -c "celery -A task_service worker -P solo --loglevel=INFO"
    environment:
      DJANGO_SETTINGS_MODULE: 'task_service.settings'
      CELERY_BROKER_URL: 'redis://redis:6379/0'
      CELERY_RESULT_BACKEND: 'redis://redis:6379/0'
    depends_on:
      - redis
    volumes:
      - ./task_service:/popug_area/task_service

  accounting_celery:
    restart: on-failure
    build: .
    working_dir: /popug_area/accounting_service
    command: bash -c "celery -A accounting_service worker -P solo --loglevel=INFO"
    environment:
      DJANGO_SETTINGS_MODULE: 'accounting_service.settings'
      CELERY_BROKER_URL: 'redis://redis:6379/1'
      CELERY_RESULT_BACKEND: 'redis://redis:6379/1'
    depends_on:
      - redis
    volumes:
      - ./accounting_service:/popug_area/accounting_service

  accounting_celery_beat:
    restart: on-failure
    build: .
    working_dir: /popug_area/accounting_service
    command: bash -c "celery -A accounting_service beat"
    environment:
      DJANGO_SETTINGS_MODULE: 'accounting_service.settings'
      CELERY_BROKER_URL: 'redis://redis:6379/1'
      CELERY_RESULT_BACKEND: 'redis://redis:6379/1'
    depends_on:
      - redis
    volumes:
      - ./accounting_service:/popug_area/accounting_service

  task_consumer:
    build: .
    restart: always
    working_dir: /task_service
    command: python manage.py runconsumer
    volumes:
      - ./task_service:/task_service
    depends_on:
      broker:
        condition: service_healthy

  accounting_consumer:
    build: .
    restart: always
    working_dir: /accounting_service
    command: python manage.py runconsumer
    volumes:
      - ./accounting_service:/accounting_service
    depends_on:
      broker:
        condition: service_healthy
