# Generated by Django 5.0.3 on 2024-03-08 06:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(editable=False, max_length=40)),
                ('public_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('MANAGER', 'MANAGER'), ('TESTER', 'TESTER'), ('DEVELOPER', 'DEVELOPER')], max_length=9)),
                ('full_name', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('COMPLETED', 'COMPLETED')], default='OPEN', max_length=9)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_tracker.user')),
            ],
        ),
    ]
